### PR TITLE
Fix build on kernel 6.3

### PR DESCRIPTION
**Pull request by endrift**
This fixes compilation on 6.3. There have been conflicting reports as to whether or not the driver actually works afterwards, however.

### CODE REVIEW

**Comment by webodan** [comment]
thanks a lot! confirmed working on 6.3.0-x64v3-xanmod1!

honestly, this driver should just be mainlined, so the kernel deals with it. it provides more functionality than xpad does already and it's just as stable in my testing.

medusalix shouldn't have to bother with it anymore if he has no time or interest.

**Comment by vlad2305m** [comment]
Typing "const " while my package manager was rebuilding the thing was such a silly thing to do, but I'm glad that it worked. Thank you!
(linux v 6.3.1.arch1-1)

**Comment by KyrillGobber** [comment]
Totally works on 6.3.1-zen1-1-zen, thank you very much

**Comment by lostiniceland** [comment]
Confirmed working on openSuse Tumbleweed

**Comment by KaiserBh** [comment]
Can confirm this works, thanks.
```prolog
OS: Arch Linux x86_64
Host: MS-7C91 2.0
Kernel: 6.3.1-zen1-1-zen
```

**Comment by scoobery** [comment]
Can also confirm this fixed my compile issue on 6.3.1-artix1-1

**Comment by viktorbahr** [comment]
Confirmed working on `6.3.1-arch2-1`. Fixes defunct driver (as tested on [2467407](https://github.com/medusalix/xone/commit/24674076034e21d99e5e09f9b5fbbeaf21a5f8b4)).

**Comment by Vaargk** [comment]
For me it doesn't build, neither the current medusalix/xone commit nor from endrift, dunno if I do sth. wrong (6.3.1-arch2-1):

<details>
<summary>Build log</summary>

   ```
Installing xone v0.3-1-g2467407...
Sign command: /usr/lib/modules/6.3.1-arch2-1/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub
Creating symlink /var/lib/dkms/xone/v0.3-1-g2467407/source -> /usr/src/xone-v0.3-1-g2467407

Building module:
Cleaning build area...
make -j12 KERNELRELEASE=6.3.1-arch2-1 -C /usr/lib/modules/6.3.1-arch2-1/build M=/var/lib/dkms/xone/v0.3-1-g2467407/build...(bad exit status: 2)
Error! Bad return status for module build on kernel: 6.3.1-arch2-1 (x86_64)
Consult /var/lib/dkms/xone/v0.3-1-g2467407/build/make.log for more information.
DKMS make.log for xone-v0.3-1-g2467407 for kernel 6.3.1-arch2-1 (x86_64)
Sat May 13 12:33:11 PM CEST 2023
  CC [M]  /var/lib/dkms/xone/v0.3-1-g2467407/build/transport/wired.o
  CC [M]  /var/lib/dkms/xone/v0.3-1-g2467407/build/transport/dongle.o
  CC [M]  /var/lib/dkms/xone/v0.3-1-g2467407/build/transport/mt76.o
  CC [M]  /var/lib/dkms/xone/v0.3-1-g2467407/build/bus/bus.o
  CC [M]  /var/lib/dkms/xone/v0.3-1-g2467407/build/bus/protocol.o
  CC [M]  /var/lib/dkms/xone/v0.3-1-g2467407/build/driver/common.o
  CC [M]  /var/lib/dkms/xone/v0.3-1-g2467407/build/driver/gamepad.o
  CC [M]  /var/lib/dkms/xone/v0.3-1-g2467407/build/driver/headset.o
  CC [M]  /var/lib/dkms/xone/v0.3-1-g2467407/build/driver/chatpad.o
  CC [M]  /var/lib/dkms/xone/v0.3-1-g2467407/build/driver/guitar.o
/var/lib/dkms/xone/v0.3-1-g2467407/build/bus/bus.c:91:19: error: initialization of ‘int (*)(const struct device *, struct kobj_uevent_env *)’ from incompatible pointer type ‘int (*)(struct device *, struct kobj_uevent_env *)’ [-Werror=incompatible-pointer-types]
   91 |         .uevent = gip_client_uevent,
      |                   ^~~~~~~~~~~~~~~~~
/var/lib/dkms/xone/v0.3-1-g2467407/build/bus/bus.c:91:19: note: (near initialization for ‘gip_client_type.uevent’)
cc1: some warnings being treated as errors
make[1]: *** [scripts/Makefile.build:252: /var/lib/dkms/xone/v0.3-1-g2467407/build/bus/bus.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:2025: /var/lib/dkms/xone/v0.3-1-g2467407/build] Error 2
Time: 0h:00m:03s
```
</details>

**Comment by Vaargk** [comment]
Agree, works on ```6.3.1-arch2-1```, merge to master would be awesome!

**Comment by medusalix** [comment]
Thanks
