### PR TITLE
fix: build on kernel v6.12

### PR DESCRIPTION
**Pull request by tskaar**
Fixes the build issues related to: 
```C
snd_pcm_lib_alloc_vmalloc_buffer()
snd_pcm_lib_free_vmalloc_buffer()
snd_pcm_lib_get_vmalloc_page()
```
On kernel v6.12-rc1

The change for the helper can be found at ["Drop of obsoloted vmalloc PCM buffer helper API"](https://lore.kernel.org/all/20240807152725.18948-3-tiwai@suse.de/) and the code that I implemented here was taken from the driver [here](https://lore.kernel.org/all/20240807152725.18948-2-tiwai@suse.de/)

This also depends on the PR https://github.com/medusalix/xone/pull/48 for the v6.11 build fix.

Note: I don't have a headset to verify that the driver is working as expected, I only made the necessary changes to get it to build!

### CODE REVIEW

**Comment by dlundqvist** [comment]
I'll verify this once 6.12 lands in Debian experimental.

**Comment by claybie** [comment]
Working here on linux-tkg 6.12-rc1

**Comment by gbluma** [comment]
Just adding another data point: I can confirm that the 6.11 fix worked for me (linux kernel 6.11.1-zen1-1-zen)

**Comment by nul9o9** [comment]
This worked for me as well, on kernel 6.11.1-arch1-1.

**Comment by lostiniceland** [comment]
Works on Suse Tumbleweed

**Comment by BeiNacht** [comment]
Works in NixOS with 6.11 and 6.12-rc kernels

How is it with the maintenance on this project? @medusalix is there a way to help?

**Comment by sh0ra1t** [comment]
Files replaced in the original xone's folder and working properly on ArchLinux with 6.11.3-arch1-1.

**Comment by TarsiSurdi** [comment]
Confirmed working on Fedora 41 beta (kernel 6.11.3). Thank you for opening this PR 👏!

**Comment by hajnal-endot** [comment]
Confirmed working on Fedora 40, as well (we just got 6.11.3 a day or so ago).

**Comment by wayneyaoo** [comment]
Confirmed working on Debian Testing 6.11.2 (just got it today). Thank you for the PR :)

**Comment by tyumici** [comment]
> Files replaced in the original xone's folder and working properly on ArchLinux with 6.11.3-arch1-1.

Confirming this as well

**Comment by GarethTheNerd** [comment]
Working on Fedora 41 KDE

**Comment by Juts2** [comment]
Confirmed working on 6.12

OS: CachyOS Linux x86_64
Host: X870E Taichi Lite
Kernel: Linux 6.12.0-rc7-1-cachyos-autofdo

**Comment by prystoynyy** [comment]
Confirmed working on 6.11

OS: Fedora 41 Gnome
Kernel: 6.11.7-300.fc41.x86_64

**Comment by Mike710Shine** [comment]
Confirmed working on 6.12.0-2-cachyos

OS: CachyOS
Kernel: 6.12.0-2-cachyos (64-bit)

**Comment by bursterburster** [comment]
Confirmed working on Arch, 6.12.1-zen.

**Comment by adamdmoss** [comment]
confirmed working on ubuntu, 6.11.0-1009-oem

**Comment by jmfergeau** [comment]
I want to install this but i'm getting an error:

```
Building module(s).....(bad exit status: 2)
Failed command:
make -j6 KERNELRELEASE=6.12.4-1-MANJARO -C /usr/lib/modules/6.12.4-1-MANJARO/build M=/var/lib/dkms/xone/unknown/build

Error! Bad return status for module build on kernel: 6.12.4-1-MANJARO (x86_64)
Consult /var/lib/dkms/xone/unknown/build/make.log for more information.
DKMS make.log for xone/unknown for kernel 6.12.4-1-MANJARO (x86_64)
mar. 17 déc. 2024 11:50:59 CET
make : on entre dans le répertoire « /usr/lib/modules/6.12.4-1-MANJARO/build »
  CC [M]  /var/lib/dkms/xone/unknown/build/transport/wired.o
  CC [M]  /var/lib/dkms/xone/unknown/build/transport/dongle.o
  CC [M]  /var/lib/dkms/xone/unknown/build/transport/mt76.o
  CC [M]  /var/lib/dkms/xone/unknown/build/bus/bus.o
  CC [M]  /var/lib/dkms/xone/unknown/build/bus/protocol.o
  CC [M]  /var/lib/dkms/xone/unknown/build/auth/auth.o
/var/lib/dkms/xone/unknown/build/bus/bus.c:126:18: erreur: initialisation de « int (*)(struct device *, const struct device_driver *) » depuis le type pointeur « int (*)(struct device *, struct device_driver *) » qui est incompatible [-Wincompatible-pointer-types]
  126 |         .match = gip_bus_match,
      |                  ^~~~~~~~~~~~~
/var/lib/dkms/xone/unknown/build/bus/bus.c:126:18: note: (près de l'initialisation de « gip_bus_type.match »)
make[2]: *** [scripts/Makefile.build:229: /var/lib/dkms/xone/unknown/build/bus/bus.o] Error 1
make[2]: *** Attente des tâches non terminées....
make[1]: *** [/usr/lib/modules/6.12.4-1-MANJARO/build/Makefile:1936: /var/lib/dkms/xone/unknown/build] Error 2
make: *** [Makefile:224: __sub-make] Error 2
make : on quitte le répertoire « /usr/lib/modules/6.12.4-1-MANJARO/build »
```

**Comment by tskaar** [comment]
@jmfergeau

I suspect that you haven't merged the patch(es) before building?
You can either check out my branch directly and build from there, or merge my branch on top of main here

**Comment by zolotvok** [comment]
I cloned your repository with `git clone https://github.com/tskaar/xone
` but when I tried to install it, got this error message

`Building module(s)....(bad exit status: 2)
Failed command:
make -j16 KERNELRELEASE=6.12.4-200.fc41.x86_64 -C /lib/modules/6.12.4-200.fc41.x86_64/build M=/var/lib/dkms/xone/unknown/build

Error! Bad return status for module build on kernel: 6.12.4-200.fc41.x86_64 (x86_64)
Consult /var/lib/dkms/xone/unknown/build/make.log for more information.
DKMS make.log for xone/unknown for kernel 6.12.4-200.fc41.x86_64 (x86_64)
Tue Dec 17 06:23:36 PM CET 2024
make: Entering directory '/usr/src/kernels/6.12.4-200.fc41.x86_64'
  CC [M]  /var/lib/dkms/xone/unknown/build/transport/wired.o
  CC [M]  /var/lib/dkms/xone/unknown/build/transport/dongle.o
  CC [M]  /var/lib/dkms/xone/unknown/build/transport/mt76.o
  CC [M]  /var/lib/dkms/xone/unknown/build/bus/bus.o
  CC [M]  /var/lib/dkms/xone/unknown/build/bus/protocol.o
  CC [M]  /var/lib/dkms/xone/unknown/build/auth/auth.o
  CC [M]  /var/lib/dkms/xone/unknown/build/auth/crypto.o
  CC [M]  /var/lib/dkms/xone/unknown/build/driver/common.o
  CC [M]  /var/lib/dkms/xone/unknown/build/driver/gamepad.o
  CC [M]  /var/lib/dkms/xone/unknown/build/driver/headset.o
  CC [M]  /var/lib/dkms/xone/unknown/build/driver/chatpad.o
  CC [M]  /var/lib/dkms/xone/unknown/build/driver/madcatz_strat.o
  CC [M]  /var/lib/dkms/xone/unknown/build/driver/madcatz_glam.o
  CC [M]  /var/lib/dkms/xone/unknown/build/driver/pdp_jaguar.o
  LD [M]  /var/lib/dkms/xone/unknown/build/xone-gip-gamepad.o
/var/lib/dkms/xone/unknown/build/bus/bus.c:126:18: error: initialization of ‘int (*)(struct device *, const struct device_driver *)’ from incompatible pointer type ‘int (*)(struct device *, struct device_driver *)’ [-Wincompatible-pointer-types]
  126 |         .match = gip_bus_match,
      |                  ^~~~~~~~~~~~~
/var/lib/dkms/xone/unknown/build/bus/bus.c:126:18: note: (near initialization for ‘gip_bus_type.match’)
make[2]: *** [scripts/Makefile.build:229: /var/lib/dkms/xone/unknown/build/bus/bus.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/var/lib/dkms/xone/unknown/build/driver/headset.c: In function ‘gip_headset_pcm_hw_params’:
/var/lib/dkms/xone/unknown/build/driver/headset.c:93:16: error: implicit declaration of function ‘snd_pcm_lib_alloc_vmalloc_buffer’ [-Wimplicit-function-declaration]
   93 |         return snd_pcm_lib_alloc_vmalloc_buffer(sub,
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/xone/unknown/build/driver/headset.c: In function ‘gip_headset_pcm_hw_free’:
/var/lib/dkms/xone/unknown/build/driver/headset.c:99:16: error: implicit declaration of function ‘snd_pcm_lib_free_vmalloc_buffer’; did you mean ‘snd_pcm_lib_malloc_pages’? [-Wimplicit-function-declaration]
   99 |         return snd_pcm_lib_free_vmalloc_buffer(sub);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                snd_pcm_lib_malloc_pages
/var/lib/dkms/xone/unknown/build/driver/headset.c: At top level:
/var/lib/dkms/xone/unknown/build/driver/headset.c:160:17: error: ‘snd_pcm_lib_get_vmalloc_page’ undeclared here (not in a function); did you mean ‘snd_pcm_lib_malloc_pages’?
  160 |         .page = snd_pcm_lib_get_vmalloc_page,
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                 snd_pcm_lib_malloc_pages
make[2]: *** [scripts/Makefile.build:229: /var/lib/dkms/xone/unknown/build/driver/headset.o] Error 1
make[1]: *** [/usr/src/kernels/6.12.4-200.fc41.x86_64/Makefile:1976: /var/lib/dkms/xone/unknown/build] Error 2
make: *** [Makefile:236: __sub-make] Error 2
make: Leaving directory '/usr/src/kernels/6.12.4-200.fc41.x86_64'
`

**Comment by tskaar** [comment]
@zolotvok;

You need to clone the specific branch, and not main: Main is currently tracking the xone repo 1:1, hence it has the same issue, retry with either:

`git clone https://github.com/tskaar/xone -b fix-6.12`,
Or go into your pulled git repo and run:

`git switch fix-6.12`

**Comment by Kidlike** [comment]
Confirming that this fixes the core functionality on Fedora 41 and kernel 6.12.

BUT, there used to be some features on kernel 6.9 that don't work anymore:
- **on system shutdown, xone was sending a poweroff signal to all connected controllers, so they also shutdown**
- controller input used to be recognized as system activity. Now, if the only active input is the controller, the system goes to sleep or screen-off, according on power management settings.

**Comment by Juts2** [comment]
> * controller input used to be recognized as system activity. Now, if the only active input is the controller, the system goes to sleep or screen-off, according on power management settings.

This is a kde bug they have finally announced they are working on. Been that way for a decade. https://bugs.kde.org/show_bug.cgi?id=328987

Any workarounds were likely using utilities like joystickwake

**Comment by Kidlike** [comment]
> > * controller input used to be recognized as system activity. Now, if the only active input is the controller, the system goes to sleep or screen-off, according on power management settings.
> 
> This is a kde bug they have finally announced they are working on. Been that way for a decade. https://bugs.kde.org/show_bug.cgi?id=328987
> 
> Any workarounds were likely using utilities like joystickwake

I probably had a workaround that I don't remember then 😅

**Comment by jmfergeau** [comment]
> @zolotvok;
> 
> You need to clone the specific branch, and not main: Main is currently tracking the xone repo 1:1, hence it has the same issue, retry with either:
> 
> `git clone https://github.com/tskaar/xone -b fix-6.12`, Or go into your pulled git repo and run:
> 
> `git switch fix-6.12`

Thanks. Silly of me, i didn't noticed there was a branch for it ^^'

It worked like a charm. Thanks. I don't get why this fix isn't pushed yet...

**Comment by PrimerFender** [comment]
Thank you this worked for me also 6.11.11-1-MANJARO

**Comment by purkhusid** [comment]
Any chance that this could be merged?

**Comment by drick0230** [comment]
Seems to work fine on:
>Fedora Linux 41 (Workstation Edition)
>Linux 6.12.7-200.fc41.x86_64

Also, it seems to fulfill the following pull-requests:
- https://github.com/medusalix/xone/pull/56
- https://github.com/medusalix/xone/pull/57

**Comment by lmReef** [comment]
working on 6.12.8-arch1-1

**Comment by k0nm4** [comment]
Works like a charm on the `6.12.8-arch1-1`, thank you so much mate!

**Comment by NotAGnelf** [comment]
works on 6.12.9-arch1-1, thanks

**Comment by lisa-lionheart** [comment]
This works perfectly on Manjaro unstable, thanks!

**Comment by shenk-i** [comment]
image
I can't install this on CachyOS right now. 6.12.9-3-cacyhos

**Comment by jmfergeau** [comment]
> I can't install this on CachyOS right now. 6.12.9-3-cacyhos

It seems you have already the old version of the module installed. Remove it completely first and try again.

**Comment by J4ckTh3R1pper** [comment]
I have failed to build module on Gentoo Linux for kernel 6.12.9-1-xanmod1
```
❯ sudo -E sh install.sh
Installing xone unknown...
The kernel is built without module signing facility, modules won't be signed
Creating symlink /var/lib/dkms/xone/unknown/source -> /usr/src/xone-unknown

Building module:
Cleaning build area...
Building module(s)...(bad exit status: 2)
Failed command:
make -j12 KERNELRELEASE=6.12.9-1-xanmod1 -C /lib/modules/6.12.9-1-xanmod1/build M=/var/lib/dkms/xone/unknown/build
Error! Bad return status for module build on kernel: 6.12.9-1-xanmod1 (x86_64)
Consult /var/lib/dkms/xone/unknown/build/make.log for more information.
DKMS make.log for xone-unknown for kernel 6.12.9-1-xanmod1 (x86_64)
Fri Jan 17 03:34:17 PM CST 2025
make: Entering directory '/usr/src/linux-6.12.9-xanmod1'
  CC [M]  /var/lib/dkms/xone/unknown/build/transport/wired.o
  CC [M]  /var/lib/dkms/xone/unknown/build/transport/dongle.o
  CC [M]  /var/lib/dkms/xone/unknown/build/transport/mt76.o
  CC [M]  /var/lib/dkms/xone/unknown/build/bus/bus.o
  CC [M]  /var/lib/dkms/xone/unknown/build/bus/protocol.o
  CC [M]  /var/lib/dkms/xone/unknown/build/auth/auth.o
  CC [M]  /var/lib/dkms/xone/unknown/build/auth/crypto.o
  CC [M]  /var/lib/dkms/xone/unknown/build/driver/common.o
  CC [M]  /var/lib/dkms/xone/unknown/build/driver/gamepad.o
  CC [M]  /var/lib/dkms/xone/unknown/build/driver/headset.o
  CC [M]  /var/lib/dkms/xone/unknown/build/driver/chatpad.o
  CC [M]  /var/lib/dkms/xone/unknown/build/driver/madcatz_strat.o
  CC [M]  /var/lib/dkms/xone/unknown/build/driver/madcatz_glam.o
  CC [M]  /var/lib/dkms/xone/unknown/build/driver/pdp_jaguar.o
  LD [M]  /var/lib/dkms/xone/unknown/build/xone-gip-madcatz-strat.o
  LD [M]  /var/lib/dkms/xone/unknown/build/xone-gip-gamepad.o
  LD [M]  /var/lib/dkms/xone/unknown/build/xone-wired.o
In function ‘gip_send_pkt’,
    inlined from ‘gip_request_identification’ at /var/lib/dkms/xone/unknown/build/bus/protocol.c:417:9,
    inlined from ‘gip_handle_pkt_announce’ at /var/lib/dkms/xone/unknown/build/bus/protocol.c:1081:9,
    inlined from ‘gip_dispatch_pkt.part.0.isra’ at /var/lib/dkms/xone/unknown/build/bus/protocol.c:1413:11:
/var/lib/dkms/xone/unknown/build/bus/protocol.c:382:9: error: argument 2 null where non-null expected [-Werror=nonnull]
  382 |         memcpy(client->chunk_buf_in->data, data, hdr->chunk_offset);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ./arch/x86/include/asm/string.h:5,
                 from ./arch/x86/include/asm/cpuid.h:9,
                 from ./arch/x86/include/asm/processor.h:19,
                 from ./arch/x86/include/asm/cpufeature.h:5,
                 from ./arch/x86/include/asm/thread_info.h:59,
                 from ./include/linux/thread_info.h:60,
                 from ./include/linux/spinlock.h:60,
                 from ./include/linux/mmzone.h:8,
                 from ./include/linux/gfp.h:7,
                 from ./include/linux/slab.h:16,
                 from /var/lib/dkms/xone/unknown/build/bus/protocol.c:6:
./arch/x86/include/asm/string_64.h: In function ‘gip_dispatch_pkt.part.0.isra’:
./arch/x86/include/asm/string_64.h:18:14: note: in a call to function ‘memcpy’ declared ‘nonnull’
   18 | extern void *memcpy(void *to, const void *from, size_t len);
      |              ^~~~~~
  LD [M]  /var/lib/dkms/xone/unknown/build/xone-gip-chatpad.o
  LD [M]  /var/lib/dkms/xone/unknown/build/xone-gip-headset.o
cc1: all warnings being treated as errors
make[2]: *** [scripts/Makefile.build:229: /var/lib/dkms/xone/unknown/build/bus/protocol.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [/usr/src/linux-6.12.9-xanmod1/Makefile:1937: /var/lib/dkms/xone/unknown/build] Error 2
make: *** [Makefile:224: __sub-make] Error 2
make: Leaving directory '/usr/src/linux-6.12.9-xanmod1'```

**Comment by tskaar** [comment]
@J4ckTh3R1pper;
 
 I tried with just installing linux-xanmod from Chaotic-AUR and it works as expected here:
 ```
 (4/7) Install DKMS modules
==> dkms install --no-depmod xpad-noone-git/r8.6970c40 -k 6.12.10-x64v3-xanmod1-1-edge-x64v3
==> dkms install --no-depmod hid-xpadneo/0.9.r214.g8d20a23 -k 6.12.10-x64v3-xanmod1-1-edge-x64v3
==> dkms install --no-depmod xone/0.3.r59.gd88ea1e -k 6.12.10-x64v3-xanmod1-1-edge-x64v3
==> depmod 6.12.10-x64v3-xanmod1-1-edge-x64v3
```

Don't think this is something that this patchset is triggering, so I dunno what went wrong here :shrug:

**Comment by lostiniceland** [comment]
Unfortunately this fix is not working with the latest 6.13 kernel. My Thrustmaster Controller is not working after the latest openSuse Tumbleweed update.
The controller itself gets recognized in KDE system settings, but no input are recognized.

**Comment by tskaar** [comment]
> Unfortunately this fix is not working with the latest 6.13 kernel. 

Haven't tested the driver on kernel v6.13, so other changes might've broken some other parts of this driver.
Still, that's out-of-scope for this patchset (unless this patchset is the one that is actively breaking it of course)

**Comment by J4ckTh3R1pper** [comment]
> @J4ckTh3R1pper;
> 
> I tried with just installing linux-xanmod from Chaotic-AUR and it works as expected here:
> 
> ```
> (4/7) Install DKMS modules
> ==> dkms install --no-depmod xpad-noone-git/r8.6970c40 -k 6.12.10-x64v3-xanmod1-1-edge-x64v3
> ==> dkms install --no-depmod hid-xpadneo/0.9.r214.g8d20a23 -k 6.12.10-x64v3-xanmod1-1-edge-x64v3
> ==> dkms install --no-depmod xone/0.3.r59.gd88ea1e -k 6.12.10-x64v3-xanmod1-1-edge-x64v3
> ==> depmod 6.12.10-x64v3-xanmod1-1-edge-x64v3
> ```
> 
> Don't think this is something that this patchset is triggering, so I dunno what went wrong here 🤷

I added -Werror=nonnull parameter and it works as expected, looks like my GCC is somehow obsessed with null arguments.

**Comment by lostiniceland** [comment]
> > Unfortunately this fix is not working with the latest 6.13 kernel.
> 
> Haven't tested the driver on kernel v6.13, so other changes might've broken some other parts of this driver. Still, that's out-of-scope for this patchset (unless this patchset is the one that is actively breaking it of course)

That's what I've expected, but I thought to put the info here since this is currently the most active place and your fork doesn't have issues activated as far as I could tell.
Nevertheless, thanks for your efforts.

**Comment by tskaar** [comment]
Yeah, this current PR is _almost_ acting like an issue discussion since there is no official issue support on this repository

Might be worthwile to open an issue ticket on dlundqvists's fork (which includes this patchset here), such that other people can chime in with potential (future) issues:

https://github.com/dlundqvist/xone/issues

**Comment by lostiniceland** [comment]
6.13 issue created https://github.com/dlundqvist/xone/issues/31

**Comment by Instinctlol** [comment]
I haven't extensively tested this yet, but so far it seems to work fine with my original xbox one wireless adapter and original xbox one controller on `6.13.1-arch1-1`

**Comment by tskaar** [comment]
@lostiniceland

I tested my Xbox controller (Model 1697) using the wireless adapter v2, and the xbox controller is connecting and working as expected on linux-mainline (6.13.0-1-mainline) on Arch

Edit:
Also works on kernel v6.14.0-rc1

**Comment by lostiniceland** [comment]
@tskaar 

I did some more testing on another machine which runs the same OS but a official Microsoft controller and there everything works.
I've adjusted the issue to be specific for the Thrustmaster controller.

**Comment by decmade** [comment]
What else is need to get this merged?

**Comment by lionking102** [comment]
Would be great if we can get this in an official release. This software is so important for people coming to linux and want to use their controller.

**Comment by lmReef** [comment]
very much still working on Linux 6.13.1-arch1-1

**Comment by FabienDanieau** [comment]
working on debian bookworm with linux-image-6.12.9+bpo-amd64. thanks!

**Comment by soderluk** [comment]
Confirming it works on Pop!_OS 24.04 LTS COSMIC 6.12.10-76061203-generic. Thank very much!

**Review by decmade — APPROVED** [review]

**Comment by BentiGorlich** [comment]
Works on Fedora41 `6.13.4-200.fc41.x86_64` :heart:

**Comment by vipau** [comment]
Works on Fedora 41 with 6.13.8-200.fc41.x86_64  
This should really get merged!

**Comment by Lawstorant** [comment]
author is MIA and project is dead, please open PRs to https://github.com/dlundqvist/xone

This is an active and maintained fork
